[package]
name = "dw1000-rs"
version = "0.1.0"
edition = "2021"
authors = ["Nicolas Farabegoli"]
license = "Apache-2.0"
description = "Embedded Rust driver for the Decawave DW1000 UWB transceiver"
repository = "https://github.com/nicolasfara/dw1000-rs"
keywords = ["embedded", "uwb", "dw1000", "driver", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
embedded-hal = "1.0.0"
embassy-time = { version = "0.3.0"}
defmt = { version = "0.3", optional = true }
libm = "0.2"
heapless = "0.9.1"
rand_core = "0.9.3"

[features]
default = []
legacy-examples = []

[[example]]
name = "anchor"
required-features = ["legacy-examples"]

[[example]]
name = "tag"
required-features = ["legacy-examples"]

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
