#![no_std]

mod app;
mod board;
pub mod nodes;

use app::RangingApp;
use board::Board;
use dw1000_rs::Role;
use nodes::NodeConfig;

// TAG_SLOT_COUNT and TAG_SLOT_MS, shared by every node on the PAN, are
// generated by build.rs from DW1000_TAG_SLOT_COUNT / DW1000_TAG_SLOT_MS.
include!(concat!(env!("OUT_DIR"), "/schedule_config.rs"));

const PEER_CAPACITY: usize = 4;
const RX_BUFFER_LEN: usize = 127;
const DW1000_SPI_BAUD_HZ: u32 = 3_000_000;
const STM6600_BOOT_TIMEOUT_MS: u64 = 1_000;
const DW1000_LINK_RECOVERY_TIMEOUT_MS: u32 = 1_000;
const RANGING_REPLY_DELAY_US: u16 = 7_000;
const RANGING_EXCHANGE_TIMEOUT_MS: u32 = 500;
const RANGING_SESSION_TIMEOUT_MS: u32 = 80;
const RANGING_PERIOD_MS: u32 = 250;
const PEER_INACTIVITY_TIMEOUT_MS: u32 = 3_000;
const FAULT_LED_ON_MS: u64 = 120;
const FAULT_LED_OFF_MS: u64 = 120;
const FAULT_LED_PAUSE_MS: u64 = 700;
const FAULT_BLINK_COUNT: usize = 3;

const _: () =
    assert!(RANGING_REPLY_DELAY_US as u32 * (PEER_CAPACITY as u32 * 2 - 1) <= u16::MAX as u32);

pub async fn run(role: Role, node_config: NodeConfig) -> ! {
    let board = match Board::init().await {
        Ok(board) => board,
        Err(error) => error.fault_loop().await,
    };

    let app = match RangingApp::<PEER_CAPACITY>::new(board, role, node_config).await {
        Ok(app) => app,
        Err(error) => error.fault_loop().await,
    };

    app.run_forever().await
}
