[package]
name = "dw1000-embassy-stm32l432"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-hal-bus = { version = "0.3.0", features = ["async"] }
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-futures = "0.1.2"
embassy-stm32 = { version = "0.4.0", features = ["stm32l432kc", "defmt", "unstable-pac", "exti", "time-driver-tim1"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
dw1000-rs = { path = "../..", features = ["defmt"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2
